In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets 

In [2]:
wine=pd.read_csv("winequality-red.csv")
wine.head(4)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6

In [3]:
mean_value=np.mean(wine)                        #mean
print(mean_value)

fixed acidity            8.319637
volatile acidity         0.527821
citric acid              0.270976
residual sugar           2.538806
chlorides                0.087467
free sulfur dioxide     15.874922
total sulfur dioxide    46.467792
density                  0.996747
pH                       3.311113
sulphates                0.658149
alcohol                 10.422983
quality                  5.636023
dtype: float64


In [4]:
std_value=np.std(wine)                 #standard deviation
print(std_value)

fixed acidity            1.740552
volatile acidity         0.179004
citric acid              0.194740
residual sugar           1.409487
chlorides                0.047051
free sulfur dioxide     10.456886
total sulfur dioxide    32.885037
density                  0.001887
pH                       0.154338
sulphates                0.169454
alcohol                  1.065334
quality                  0.807317
dtype: float64


In [5]:
var_value=np.var(wine)                 #variance
print(var_value)

fixed acidity              3.029521
volatile acidity           0.032042
citric acid                0.037924
residual sugar             1.986654
chlorides                  0.002214
free sulfur dioxide      109.346457
total sulfur dioxide    1081.425636
density                    0.000004
pH                         0.023820
sulphates                  0.028715
alcohol                    1.134937
quality                    0.651761
dtype: float64


In [6]:
print(np.random.randint(1,5,20))                     #generating 20 random values in range [1,5)

[3 3 4 3 1 3 4 2 2 1 1 2 2 3 2 1 4 4 1 1]


In [7]:
matrix=np.array(wine)                                #array wine data is copied into matrix numpy array
print(matrix)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [8]:
print(np.add(matrix,matrix))                 #addition of two matrix
print(np.subtract(matrix,matrix))              #substraction of two matrix
print(matrix*matrix)                         #multiplication of two matrix

[[14.8   1.4   0.   ...  1.12 18.8  10.  ]
 [15.6   1.76  0.   ...  1.36 19.6  10.  ]
 [15.6   1.52  0.08 ...  1.3  19.6  10.  ]
 ...
 [12.6   1.02  0.26 ...  1.5  22.   12.  ]
 [11.8   1.29  0.24 ...  1.42 20.4  10.  ]
 [12.    0.62  0.94 ...  1.32 22.   12.  ]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[5.47600e+01 4.90000e-01 0.00000e+00 ... 3.13600e-01 8.83600e+01
  2.50000e+01]
 [6.08400e+01 7.74400e-01 0.00000e+00 ... 4.62400e-01 9.60400e+01
  2.50000e+01]
 [6.08400e+01 5.77600e-01 1.60000e-03 ... 4.22500e-01 9.60400e+01
  2.50000e+01]
 ...
 [3.96900e+01 2.60100e-01 1.69000e-02 ... 5.62500e-01 1.21000e+02
  3.60000e+01]
 [3.48100e+01 4.16025e-01 1.44000e-02 ... 5.04100e-01 1.04040e+02
  2.50000e+01]
 [3.60000e+01 9.61000e-02 2.20900e-01 ... 4.35600e-01 1.21000e+02
  3.60000e+01]]


In [9]:
matrix=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [10]:
eigen_value ,eigen_vector=np.linalg.eig(matrix)        #finding eigen values and eigen vector
print(eigen_value)
print(eigen_vector)

[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(np.linalg.inv(matrix))                           #inverse of matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
matrix=matrix.reshape(1,-1)               #conversion of 2d to 1d matrix
print(matrix)

[[1 0 0 0 1 0 0 0 1]]


In [13]:
from sklearn import preprocessing
coder= preprocessing.LabelEncoder()                 #it is used to encode string datatype into numbers
ans=coder.fit_transform(['Ram','Mohan','shyam','Rahul','chitra','samurk','Ram'])
print(ans)

[2 0 5 1 3 4 2]


In [14]:
from sklearn.model_selection import train_test_split
target=wine["quality"].values
features=wine.drop(['quality'],axis=1).values
X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.25,random_state=42)

In [15]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[11.7   0.49  0.49 ...  3.19  0.43  9.2 ]
 [ 8.8   0.6   0.29 ...  3.36  0.49  9.1 ]
 [ 7.1   0.59  0.   ...  3.42  0.55 11.5 ]
 ...
 [ 7.2   0.62  0.06 ...  3.51  0.54  9.5 ]
 [ 7.9   0.2   0.35 ...  3.32  0.8  11.9 ]
 [ 5.8   0.29  0.26 ...  3.39  0.54 13.5 ]]
[[ 7.7   0.56  0.08 ...  3.24  0.66  9.6 ]
 [ 7.8   0.5   0.17 ...  3.39  0.48  9.5 ]
 [10.7   0.67  0.22 ...  3.28  0.98  9.9 ]
 ...
 [ 7.1   0.6   0.   ...  3.47  0.7   9.9 ]
 [ 7.8   0.62  0.05 ...  3.29  0.63  9.3 ]
 [10.6   0.36  0.57 ...  3.14  0.72 11.1 ]]
[5 5 7 ... 5 7 6]
[6 5 6 5 6 5 5 5 5 6 7 3 5 5 6 7 5 7 8 5 5 6 5 6 6 6 7 6 5 6 5 5 6 5 6 5 7
 5 4 6 5 5 7 5 5 6 7 6 5 6 5 5 5 7 6 6 6 5 5 5 5 7 5 6 6 5 6 5 6 5 6 4 6 6
 6 5 8 5 6 6 5 6 5 6 6 7 5 6 7 4 7 6 5 5 5 6 5 6 5 6 5 5 5 7 6 7 6 5 6 5 8
 5 6 5 6 7 6 6 5 6 6 6 6 6 6 6 7 6 5 5 6 5 5 5 6 5 5 5 5 6 7 6 8 5 5 5 6 6
 6 5 6 7 6 5 6 5 5 6 6 6 7 5 7 5 5 5 6 6 5 5 6 5 7 6 7 6 6 5 5 6 4 6 5 7 5
 5 4 5 7 6 5 6 6 7 6 5 5 6 5 7 5 6 6 5 7 5 5 5 6 7 7 5 5 6 6 7 6 5 6 6 6 6
 6 7

In [16]:
from sklearn import preprocessing                                           #importing preprocessing library
quantile_transformer = preprocessing.QuantileTransformer(random_state=45)         #Quantile transformer is used in mapping
X_train_trans = quantile_transformer.fit_transform(X_train)
X_test_trans = quantile_transformer.transform(X_test)
np.percentile(X_train[:, 0], [0, 25, 50, 75, 100])

array([ 4.6,  7.1,  7.9,  9.2, 15.9])

In [17]:
#KNeighboursClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
#create object of the classifier
neigh = KNeighborsClassifier(n_neighbors=2)
#Train the algorithm
neigh.fit(X_train, y_train)
# predict the response
pred = neigh.predict(X_test)
# evaluate accuracy
print ("KNeighbors accuracy score : ",accuracy_score(y_test, pred))

KNeighbors accuracy score :  0.4425


In [18]:
#svm and score of svm
from sklearn import svm
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, features,target, cv=5)
print(scores)


[0.54375    0.521875   0.60625    0.5875     0.59874608]


In [19]:
#Linear Regression
from sklearn.linear_model import LinearRegression
reg_all=LinearRegression()
reg_all.fit(X_train,y_train)
y_pred=reg_all.predict(X_test)
accu=reg_all.score(X_test,y_test)
y_test=y_test.astype(float);
print('accurancy of linear model is:{}'.format(accu))
print(y_test)

accurancy of linear model is:0.3722831200818101
[6. 5. 6. 5. 6. 5. 5. 5. 5. 6. 7. 3. 5. 5. 6. 7. 5. 7. 8. 5. 5. 6. 5. 6.
 6. 6. 7. 6. 5. 6. 5. 5. 6. 5. 6. 5. 7. 5. 4. 6. 5. 5. 7. 5. 5. 6. 7. 6.
 5. 6. 5. 5. 5. 7. 6. 6. 6. 5. 5. 5. 5. 7. 5. 6. 6. 5. 6. 5. 6. 5. 6. 4.
 6. 6. 6. 5. 8. 5. 6. 6. 5. 6. 5. 6. 6. 7. 5. 6. 7. 4. 7. 6. 5. 5. 5. 6.
 5. 6. 5. 6. 5. 5. 5. 7. 6. 7. 6. 5. 6. 5. 8. 5. 6. 5. 6. 7. 6. 6. 5. 6.
 6. 6. 6. 6. 6. 6. 7. 6. 5. 5. 6. 5. 5. 5. 6. 5. 5. 5. 5. 6. 7. 6. 8. 5.
 5. 5. 6. 6. 6. 5. 6. 7. 6. 5. 6. 5. 5. 6. 6. 6. 7. 5. 7. 5. 5. 5. 6. 6.
 5. 5. 6. 5. 7. 6. 7. 6. 6. 5. 5. 6. 4. 6. 5. 7. 5. 5. 4. 5. 7. 6. 5. 6.
 6. 7. 6. 5. 5. 6. 5. 7. 5. 6. 6. 5. 7. 5. 5. 5. 6. 7. 7. 5. 5. 6. 6. 7.
 6. 5. 6. 6. 6. 6. 6. 7. 4. 5. 5. 7. 5. 5. 5. 5. 6. 6. 5. 7. 5. 6. 6. 6.
 5. 4. 6. 7. 6. 7. 5. 6. 6. 5. 5. 6. 5. 6. 4. 5. 6. 6. 5. 6. 6. 5. 5. 6.
 7. 7. 6. 5. 6. 6. 5. 6. 5. 6. 5. 5. 5. 6. 6. 6. 7. 5. 5. 6. 5. 7. 5. 6.
 4. 6. 6. 8. 6. 5. 5. 6. 5. 7. 6. 6. 5. 5. 7. 6. 6. 5. 6. 6. 5. 7. 6. 6.
 6.

In [20]:
#max_error
from sklearn.metrics import max_error
max_error(y_test, y_pred)

2.2560232469783514

In [21]:
#mean_absolute_error
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

0.49987991229254364

In [22]:
y_test=np.ceil(y_test)
y_pred=np.ceil(y_pred)

In [23]:
 from sklearn.metrics import confusion_matrix     #confusion matrix for test and predict values
print(confusion_matrix(y_test,y_pred))

[[  0   0   0   1   0   0]
 [  0   0   2  11   0   0]
 [  0   0  12 144   8   0]
 [  0   0   5 113  51   0]
 [  0   0   0  12  36   0]
 [  0   0   0   0   5   0]]


In [24]:
#multilevel confusion matrix
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_test, y_pred)

array([[[399,   0],
        [  1,   0]],

       [[387,   0],
        [ 13,   0]],

       [[229,   7],
        [152,  12]],

       [[ 63, 168],
        [ 56, 113]],

       [[288,  64],
        [ 12,  36]],

       [[395,   0],
        [  5,   0]]], dtype=int64)

In [25]:
#matrix precision score
from sklearn import metrics
metrics.precision_score(y_test,y_pred,average="macro")

c:\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.23228569644752448